<?php
$title = 'Users';
$this->headTitle($title);
?>
<h1>
    <?php echo $this->escapeHtml($title); ?>
</h1>
<p>
    <a href="<?php echo $this->url('admin', array('action'=>'add'));?>">Add new user</a>
</p>
 
<table class="table">
<tr>
    <th>Email</th>
    <th>Enabled</th>
    <th>Role</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Created at</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($users as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->email);?></td>
    <td><?php echo $this->escapeHtml($user->enabled);?></td>
    <td><?php echo $this->escapeHtml($user->role);?></td>
    <td><?php echo $this->escapeHtml($user->firstname);?></td>
    <td><?php echo $this->escapeHtml($user->lastname);?></td>
    <td><?php echo $this->escapeHtml(date('Y-m-d H:i:s', $user->created_at));?></td>

    <td>
        <a href="<?php echo $this->url('admin',
            array('action'=>'edit', 'id' => $user->id));?>">Edit</a>
        <a href="<?php echo $this->url('admin',
            array('action'=>'delete', 'id' => $user->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>